### ISSUE TITLE
Can't play Guncaster.pk3

### ISSUE THREAD

**Issue by GeminiCrafterMan** [nvllsvm/GZDoom-Android#14] opened 2017-06-03 03:52 UTC
I believe Guncaster is for GZDOOM 3.0+, so it doesn't really matter if you can't fix it.

**Comment by nvllsvm** [comment] 2017-07-05 21:55
Duplicate of https://github.com/nvllsvm/GZDoom-Android/issues/12

**Closed by nvllsvm** 2017-07-05 21:55 UTC
