### ISSUE TITLE
Cant play Square1.pk3

### ISSUE THREAD

**Issue by alugarius** [nvllsvm/GZDoom-Android#11] opened 2017-05-27 12:30 UTC
http://adventuresofsquare.com

**Comment by doomMarine141** [comment] 2017-06-17 08:59
Square one needs gzdoom 2.4

**Comment by nvllsvm** [comment] 2017-06-17 17:03
Closing this issue since the root cause is https://github.com/nvllsvm/GZDoom-Android/issues/12

**Closed by nvllsvm** 2017-06-17 17:03 UTC
